### ISSUE TITLE
RepLib fails to build

### ISSUE THREAD

**Issue by nomeata** [sweirich/replib#32]
Hi,

on hackage, and also on some of my colleagues’ machines, RepLib fails to build.
```
[11 of 12] Compiling Generics.RepLib.Unify ( Generics/RepLib/Unify.hs, dist/build/Generics/RepLib/Unify.o )

Generics/RepLib/Unify.hs:181:28: Not in scope: ‘runExceptT’

Generics/RepLib/Unify.hs:201:28: Not in scope: ‘runExceptT’
Failed to install RepLib-0.5.3.4
cabal: Error: some packages failed to install:
```

See http://hackage.haskell.org/package/RepLib-0.5.3.4/reports/1 for the full report.

**Comment by sweirich** [comment]
I just pushed (what I hope) is a fix.  Can you get your colleagues to check? If this works, I'll upload to Hackage.

**Comment by nomeata** [comment]
@lohner, can you check?

**Comment by lohner** [comment]
Unfortunately 68218ba38ead3a86cfab2a38a2f676a17126bd02 doesn't fix the issue for me, as `cabal install RepLib` uses transformers-0.3.0.0 and mtl-2.1.3.1 on my machine.

However adding this patch seems to work:

```diff
diff --git a/RepLib/Generics/RepLib/Unify.hs b/RepLib/Generics/RepLib/Unify.hs
index f7ebc7c..b044a13 100644
--- a/RepLib/Generics/RepLib/Unify.hs
+++ b/RepLib/Generics/RepLib/Unify.hs
@@ -61,6 +61,8 @@ throwError :: UnifyError -> UM n a b
 throwError = throwE
 #else
 type UM n a b = ErrorT UnifyError (State (UnificationState n a)) b
+runExceptT :: ErrorT e m a -> m (Either e a)
+runExceptT = runErrorT
 #endif
```

**Comment by sweirich** [comment]
Ok, I've patched as above.  If you can verify, I'll push a new version to hackage.

**Comment by lohner** [comment]
Thanks. Now everything seems to work as expected.

**Comment by sweirich** [comment]
Thanks. New version on hackage.
